# Generated by Django 4.1.9 on 2023-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('shopping_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=25)),
                ('expire_date', models.DateField()),
                ('remaining', models.FloatField()),
                ('measure_unit', models.CharField(max_length=5)),
                ('quantity_alarm', models.BooleanField()),
                ('quantity_alarm_threshold', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('auth_from', models.DateTimeField()),
                ('auth_until', models.DateTimeField()),
                ('failed_attempts', models.IntegerField()),
                ('blocked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('monday_position', models.DateField()),
                ('monday_breakfast', models.CharField(max_length=500)),
                ('monday_lunch', models.CharField(max_length=500)),
                ('monday_dinner', models.CharField(max_length=500)),
                ('tuesday_breakfast', models.CharField(max_length=500)),
                ('tuesday_lunch', models.CharField(max_length=500)),
                ('tuesday_dinner', models.CharField(max_length=500)),
                ('wednesday_breakfast', models.CharField(max_length=500)),
                ('wednesday_lunch', models.CharField(max_length=500)),
                ('wednesday_dinner', models.CharField(max_length=500)),
                ('thursday_breakfast', models.CharField(max_length=500)),
                ('thursday_lunch', models.CharField(max_length=500)),
                ('thursday_dinner', models.CharField(max_length=500)),
                ('friday_breakfast', models.CharField(max_length=500)),
                ('friday_lunch', models.CharField(max_length=500)),
                ('friday_dinner', models.CharField(max_length=500)),
                ('saturday_breakfast', models.CharField(max_length=500)),
                ('saturday_lunch', models.CharField(max_length=500)),
                ('saturday_dinner', models.CharField(max_length=500)),
                ('sunday_breakfast', models.CharField(max_length=500)),
                ('sunday_lunch', models.CharField(max_length=500)),
                ('sunday_dinner', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
