# Generated by Django 4.1.9 on 2023-06-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_organizer_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('monday_position', models.DateField()),
                ('monday_breakfast', models.CharField(max_length=500)),
                ('monday_lunch', models.CharField(max_length=500)),
                ('monday_dinner', models.CharField(max_length=500)),
                ('tuesday_breakfast', models.CharField(max_length=500)),
                ('tuesday_lunch', models.CharField(max_length=500)),
                ('tuesday_dinner', models.CharField(max_length=500)),
                ('wednesday_breakfast', models.CharField(max_length=500)),
                ('wednesday_lunch', models.CharField(max_length=500)),
                ('wednesday_dinner', models.CharField(max_length=500)),
                ('thursday_breakfast', models.CharField(max_length=500)),
                ('thursday_lunch', models.CharField(max_length=500)),
                ('thursday_dinner', models.CharField(max_length=500)),
                ('friday_breakfast', models.CharField(max_length=500)),
                ('friday_lunch', models.CharField(max_length=500)),
                ('friday_dinner', models.CharField(max_length=500)),
                ('saturday_breakfast', models.CharField(max_length=500)),
                ('saturday_lunch', models.CharField(max_length=500)),
                ('saturday_dinner', models.CharField(max_length=500)),
                ('sunday_breakfast', models.CharField(max_length=500)),
                ('sunday_lunch', models.CharField(max_length=500)),
                ('sunday_dinner', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
