from django.db import models


class WeekPlan(models.Model):
    user_id = models.IntegerField()
    monday_position = models.DateField()
    monday_breakfast = models.CharField(max_length=500)
    monday_lunch = models.CharField(max_length=500)
    monday_dinner = models.CharField(max_length=500)
    tuesday_breakfast = models.CharField(max_length=500)
    tuesday_lunch = models.CharField(max_length=500)
    tuesday_dinner = models.CharField(max_length=500)
    wednesday_breakfast = models.CharField(max_length=500)
    wednesday_lunch = models.CharField(max_length=500)
    wednesday_dinner = models.CharField(max_length=500)
    thursday_breakfast = models.CharField(max_length=500)
    thursday_lunch = models.CharField(max_length=500)
    thursday_dinner = models.CharField(max_length=500)
    friday_breakfast = models.CharField(max_length=500)
    friday_lunch = models.CharField(max_length=500)
    friday_dinner = models.CharField(max_length=500)
    saturday_breakfast = models.CharField(max_length=500)
    saturday_lunch = models.CharField(max_length=500)
    saturday_dinner = models.CharField(max_length=500)
    sunday_breakfast = models.CharField(max_length=500)
    sunday_lunch = models.CharField(max_length=500)
    sunday_dinner = models.CharField(max_length=500)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
